[project]
name = "fsp-exam-flask"
version = "0.1.0"
description = "此系统为像素仙缘服务器的后端系统"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-bcrypt==1.0.1",
    "flask-cors>=5.0.0",
    "flask-login==0.6.3",
    "flask-mail>=0.10.0",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy==3.1.1",
    "gunicorn>=26.0.0",
    "jsonschema>=4.26.0",
    "pillow==11.1.0",
    "pyjwt==2.10.1",
    "pymysql>=1.2.0",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "sqlalchemy>=2.0.0",
    "toml==0.10.2",
]

[tool.ruff]
line-length = 120  # 代码最大行宽
select = [         # 选择的规则
    "F",
    "E",
    "W",
    "UP",
]
ignore = ["F401"]  # 忽略的规则

# 常见的规则如下：

# 标识   规则	                         简介
# F	    pyflakes	                    提供了一些比较基础的问题检查
# E,W	pycodestyle errors, warnings	PEP8 检查
# I	    isort	                        对 import 语句进行排序
# UP	pyupgrade	                    提示新版本的 Python 语法
# N	    pep8-naming	                    PEP8 命名规范检查
# PL	Pylint	                        知名静态代码检查器
# PERF	pyperf	                        检测一些性能问题
# RUF	Ruff	                        Ruff 社区自己实现的一些规则
