"""change background_url to LONGTEXT

Revision ID: 015f00578e0b
Revises: 72943ef8b8ce
Create Date: 2026-06-28 01:44:57.956198

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "015f00578e0b"
down_revision = "72943ef8b8ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "background_url", existing_type=mysql.TEXT(), type_=mysql.LONGTEXT(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "background_url", existing_type=mysql.LONGTEXT(), type_=mysql.TEXT(), existing_nullable=True
        )

    # ### end Alembic commands ###
