"""xxx update.

Revision ID: 0ba60cc565f9
Revises:
Create Date: 2026-06-28 00:18:06.226928

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0ba60cc565f9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activation_token", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("activation_token_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"], ondelete="CASCADE")

    with op.batch_alter_table("options", schema=None) as batch_op:
        batch_op.alter_column("is_correct", existing_type=mysql.TINYINT(display_width=1), nullable=False)

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.alter_column("logical_deletion", existing_type=mysql.TINYINT(display_width=1), nullable=False)

    with op.batch_alter_table("registration_limits", schema=None) as batch_op:
        batch_op.alter_column("register_time", existing_type=mysql.DATETIME(), nullable=False)

    with op.batch_alter_table("reset_password_token", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("reset_password_token_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"], ondelete="CASCADE")

    with op.batch_alter_table("responses", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("responses_ibfk_2"), type_="foreignkey")
        batch_op.create_foreign_key(None, "surveys", ["survey_id"], ["id"])

    with op.batch_alter_table("schematic_files", schema=None) as batch_op:
        batch_op.alter_column(
            "file_blob", existing_type=mysql.MEDIUMBLOB(), type_=sa.LargeBinary(length=524288), existing_nullable=False
        )

    with op.batch_alter_table("surveys", schema=None) as batch_op:
        batch_op.alter_column(
            "description", existing_type=mysql.TEXT(charset="utf8mb4", collation="utf8mb4_czech_ci"), nullable=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("registered_at", existing_type=mysql.DATETIME(), nullable=False)

    with op.batch_alter_table("whitelist", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=mysql.INTEGER(), nullable=False)
        batch_op.drop_constraint(batch_op.f("whitelist_ibfk_1"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"], ondelete="CASCADE")
        batch_op.create_foreign_key(None, "users", ["auditor_uid"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("whitelist", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(batch_op.f("whitelist_ibfk_1"), "users", ["user_id"], ["id"])
        batch_op.alter_column("user_id", existing_type=mysql.INTEGER(), nullable=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("registered_at", existing_type=mysql.DATETIME(), nullable=True)

    with op.batch_alter_table("surveys", schema=None) as batch_op:
        batch_op.alter_column(
            "description", existing_type=mysql.TEXT(charset="utf8mb4", collation="utf8mb4_czech_ci"), nullable=True
        )

    with op.batch_alter_table("schematic_files", schema=None) as batch_op:
        batch_op.alter_column(
            "file_blob", existing_type=sa.LargeBinary(length=524288), type_=mysql.MEDIUMBLOB(), existing_nullable=False
        )

    with op.batch_alter_table("responses", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("responses_ibfk_2"), "surveys", ["survey_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("reset_password_token", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(batch_op.f("reset_password_token_ibfk_1"), "users", ["user_id"], ["id"])

    with op.batch_alter_table("registration_limits", schema=None) as batch_op:
        batch_op.alter_column("register_time", existing_type=mysql.DATETIME(), nullable=True)

    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index("idx_question_id_logical")
        batch_op.alter_column("logical_deletion", existing_type=mysql.TINYINT(display_width=1), nullable=True)

    with op.batch_alter_table("options", schema=None) as batch_op:
        batch_op.alter_column("is_correct", existing_type=mysql.TINYINT(display_width=1), nullable=True)

    with op.batch_alter_table("activation_token", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(batch_op.f("activation_token_ibfk_1"), "users", ["user_id"], ["id"])

    # ### end Alembic commands ###
