"""问题排序字段非空

Revision ID: 1ef64e3be092
Revises: a1b1439d59dd
Create Date: 2025-04-13 20:40:56.232770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef64e3be092'
down_revision = 'a1b1439d59dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
