"""update Response is_reviewed

Revision ID: 201c056b774a
Revises: 
Create Date: 2025-03-29 18:14:43.816285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201c056b774a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('is_reviewed',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('is_reviewed',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
