"""修改图片表

Revision ID: 49109dd0ab19
Revises: 5a43be057ca4
Create Date: 2025-03-31 20:46:29.859970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49109dd0ab19'
down_revision = '5a43be057ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_img_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_img_urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('img_alt', sa.VARCHAR(length=200), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
