"""add reject_reason to responses

Revision ID: 4e8c2f9a1b0d
Revises: 015f00578e0b
Create Date: 2026-08-22 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e8c2f9a1b0d"
down_revision = "015f00578e0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("responses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reject_reason", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("responses", schema=None) as batch_op:
        batch_op.drop_column("reject_reason")

    # ### end Alembic commands ###
