"""xxx update.

Revision ID: 5a43be057ca4
Revises: 201c056b774a
Create Date: 2025-03-30 16:15:09.420123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a43be057ca4'
down_revision = '201c056b774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guarantees', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('response_details', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_reviewed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('response_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('addtime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('whitelist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('addtime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('response_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_reviewed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('response_details', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('guarantees', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
