"""add profile table

Revision ID: 72943ef8b8ce
Revises: 0ba60cc565f9
Create Date: 2026-06-28 01:17:21.762079

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "72943ef8b8ce"
down_revision = "0ba60cc565f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("background_url", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_column("background_url")

    # ### end Alembic commands ###
