"""答卷表添加审核人列

Revision ID: 7903a9663079
Revises: 9e798ccf333f
Create Date: 2025-04-27 01:08:17.436437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7903a9663079'
down_revision = '9e798ccf333f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_uid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('reviewer_uid')

    # ### end Alembic commands ###
