"""test

Revision ID: 99f168787988
Revises: 7903a9663079
Create Date: 2025-04-29 22:51:12.162431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99f168787988'
down_revision = '7903a9663079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('response_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
