"""白名单表添加来源列

Revision ID: 9e798ccf333f
Revises: ceb5f8af040b
Create Date: 2025-04-27 00:35:24.468108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e798ccf333f'
down_revision = 'ceb5f8af040b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
