"""添加归档分数和问题排序两个字段

Revision ID: a1b1439d59dd
Revises: 
Create Date: 2025-04-13 20:35:33.626548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b1439d59dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('archive_score')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
