"""修改白名单表结构

Revision ID: ceb5f8af040b
Revises: 
Create Date: 2025-04-27 00:22:54.420474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb5f8af040b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auditor_uid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('auditor_uid')

    # ### end Alembic commands ###
