"""修改问卷插槽表，breakchange！

Revision ID: df2477415a0c
Revises: 49109dd0ab19
Create Date: 2025-04-06 20:34:49.772534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2477415a0c'
down_revision = '49109dd0ab19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('survey_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
