"""修改question表字段

Revision ID: e6118fe213d8
Revises: 371cacbd5798
Create Date: 2025-04-12 21:41:17.526936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6118fe213d8'
down_revision = '371cacbd5798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logical_deletion', sa.Boolean(), nullable=True))
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###



    # ### end Alembic commands ###
